name: Rust Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run tests
        run: cargo test

      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: cargo publish || true
