name: Rust Test

on:
  push:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run tests
        run: cargo test

      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: cargo publish || true
